import '@styles/global.css'
import { AuthProvider } from '@Context/AppContext'

export const metadata = {
  title: 'Linkpath',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
